name: Test Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Tests and Report Coverage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-coverage-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-coverage-

    - name: Install package and test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Install cd-hit and mmseqs2
      run: |
        sudo apt-get update
        sudo apt-get install -y cd-hit
        sudo apt-get install -y mmseqs2

    - name: Run tests with coverage and generate XML report
      env:
        MPLBACKEND: Agg
        HYPOTHESIS_DEADLINE: 10000000
      run: |
        pytest tests --cov=./ --cov-report=xml -x -vv --durations=20

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        fail_ci_if_error: true